In [260]:
# prompt: import daata into dataframe https://drive.google.com/file/d/1NRjti1wjR0FiZ_00XxhHuRhBdZ5STtnD/view?usp=drive_link

import pandas as pd

df = pd.read_csv('tips.csv', )
print(df.head())

   total_bill   tip  gender smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15

           Payer Name     CC Number Payment ID
0  Christy Cunningham  3.560330e+15    Sun2959
1      Douglas Tucker  4.478070e+15    Sun4608
2      Travis Walters  6.011810e+15    Sun4458
3    Nathaniel Harris  4.676140e+15    Sun5260
4        Tonya Carter  4.832730e+15    Sun2251

In [261]:
print(df.columns)

Index(['total_bill', 'tip', 'gender', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [262]:
print(df.index)

RangeIndex(start=0, stop=244, step=1)

In [263]:
print(df.head())

   total_bill   tip  gender smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15

           Payer Name     CC Number Payment ID
0  Christy Cunningham  3.560330e+15    Sun2959
1      Douglas Tucker  4.478070e+15    Sun4608
2      Travis Walters  6.011810e+15    Sun4458
3    Nathaniel Harris  4.676140e+15    Sun5260
4        Tonya Carter  4.832730e+15    Sun2251

In [264]:
print(df.tail())

     total_bill   tip  gender smoker   day    time  size  price_per_person  \
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39

          Payer Name     CC Number Payment ID
239    Michael Avila  5.296070e+15    Sat2657
240   Monica Sanders  3.506810e+15    Sat1766
241       Keith Wong  6.011890e+15    Sat3880
242     Dennis Dixon  4.375220e+12      Sat17
243  Michelle Hardin  3.511450e+15    Thur672

In [265]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   gender            244 non-null    object
 3   smoker            244 non-null    object
 4   day               244 non-null    object
 5   time              244 non-null    object
 6   size              244 non-null    int64
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object
 9   CC Number         244 non-null    float64
 10  Payment ID        244 non-null    object
dtypes: float64(4), int64(1), object(6)
memory usage: 21.1+ KB
None

In [266]:
print(len(df))

244

In [267]:
print(df.describe())

       total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563495e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040732e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525320e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596450e+15

In [268]:
print(df.describe().transpose())

                  count          mean           std           min  \
total_bill        244.0  1.978594e+01  8.902412e+00  3.070000e+00
tip               244.0  2.998279e+00  1.383638e+00  1.000000e+00
size              244.0  2.569672e+00  9.510998e-01  1.000000e+00
price_per_person  244.0  7.888197e+00  2.914234e+00  2.880000e+00
CC Number         244.0  2.563495e+15  2.369340e+15  6.040679e+10

                           25%           50%           75%           max
total_bill        1.334750e+01  1.779500e+01  2.412750e+01  5.081000e+01
tip               2.000000e+00  2.900000e+00  3.562500e+00  1.000000e+01
size              2.000000e+00  2.000000e+00  3.000000e+00  6.000000e+00
price_per_person  5.800000e+00  7.255000e+00  9.390000e+00  2.027000e+01
CC Number         3.040732e+13  3.525320e+15  4.553675e+15  6.596450e+15

In [269]:
# Select a single column
print(df['total_bill'])   # print(df['first name']) -> work
print(df.total_bill)      # print(df.first name) -> Error
print(type(df['total_bill']))

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64
0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64
<class 'pandas.core.series.Series'>

In [270]:
#Select multiple columns
# Use double brackets
print(df[['total_bill','tip']])

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [271]:
#Create new columns
df['tip_percentage'] = 100 * df['tip'] / df['total_bill']
print(df.head())

   total_bill   tip  gender smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15

           Payer Name     CC Number Payment ID  tip_percentage
0  Christy Cunningham  3.560330e+15    Sun2959        5.944673
1      Douglas Tucker  4.478070e+15    Sun4608       16.054159
2      Travis Walters  6.011810e+15    Sun4458       16.658734
3    Nathaniel Harris  4.676140e+15    Sun5260       13.978041
4        Tonya Carter  4.832730e+15    Sun2251       14.680765

In [272]:
df['price_per_person'] = df['total_bill'] / df['size']
print(df.head())

   total_bill   tip  gender smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2          8.495000
1       10.34  1.66    Male     No  Sun  Dinner     3          3.446667
2       21.01  3.50    Male     No  Sun  Dinner     3          7.003333
3       23.68  3.31    Male     No  Sun  Dinner     2         11.840000
4       24.59  3.61  Female     No  Sun  Dinner     4          6.147500

           Payer Name     CC Number Payment ID  tip_percentage
0  Christy Cunningham  3.560330e+15    Sun2959        5.944673
1      Douglas Tucker  4.478070e+15    Sun4608       16.054159
2      Travis Walters  6.011810e+15    Sun4458       16.658734
3    Nathaniel Harris  4.676140e+15    Sun5260       13.978041
4        Tonya Carter  4.832730e+15    Sun2251       14.680765

In [273]:
import numpy as np
#Adjust existing columns
df['price_per_person'] = np.round(df['price_per_person'],2)
print(df.head())

   total_bill   tip  gender smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15

           Payer Name     CC Number Payment ID  tip_percentage
0  Christy Cunningham  3.560330e+15    Sun2959        5.944673
1      Douglas Tucker  4.478070e+15    Sun4608       16.054159
2      Travis Walters  6.011810e+15    Sun4458       16.658734
3    Nathaniel Harris  4.676140e+15    Sun5260       13.978041
4        Tonya Carter  4.832730e+15    Sun2251       14.680765

In [274]:
# Remove the column
df = df.drop('tip_percentage', axis=1)
print(df.head())

   total_bill   tip  gender smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15

           Payer Name     CC Number Payment ID
0  Christy Cunningham  3.560330e+15    Sun2959
1      Douglas Tucker  4.478070e+15    Sun4608
2      Travis Walters  6.011810e+15    Sun4458
3    Nathaniel Harris  4.676140e+15    Sun5260
4        Tonya Carter  4.832730e+15    Sun2251

In [275]:
# index
print(df.index)

RangeIndex(start=0, stop=244, step=1)

In [276]:
df.set_index('Payment ID', inplace=True)
print(df)

            total_bill   tip  gender smoker   day    time  size  \
Payment ID
Sun2959          16.99  1.01  Female     No   Sun  Dinner     2
Sun4608          10.34  1.66    Male     No   Sun  Dinner     3
Sun4458          21.01  3.50    Male     No   Sun  Dinner     3
Sun5260          23.68  3.31    Male     No   Sun  Dinner     2
Sun2251          24.59  3.61  Female     No   Sun  Dinner     4
...                ...   ...     ...    ...   ...     ...   ...
Sat2657          29.03  5.92    Male     No   Sat  Dinner     3
Sat1766          27.18  2.00  Female    Yes   Sat  Dinner     2
Sat3880          22.67  2.00    Male    Yes   Sat  Dinner     2
Sat17            17.82  1.75    Male     No   Sat  Dinner     2
Thur672          18.78  3.00  Female     No  Thur  Dinner     2

            price_per_person          Payer Name     CC Number
Payment ID
Sun2959                 8.49  Christy Cunningham  3.560330e+15
Sun4608                 3.45      Douglas Tucker  4.478070e+15
Sun4458                 7.00      Travis Walters  6.011810e+15
Sun5260                11.84    Nathaniel Harris  4.676140e+15
Sun2251                 6.15        Tonya Carter  4.832730e+15
...                      ...                 ...           ...
Sat2657                 9.68       Michael Avila  5.296070e+15
Sat1766                13.59      Monica Sanders  3.506810e+15
Sat3880                11.34          Keith Wong  6.011890e+15
Sat17                   8.91        Dennis Dixon  4.375220e+12
Thur672                 9.39     Michelle Hardin  3.511450e+15

[244 rows x 10 columns]

In [277]:
df.reset_index(inplace=True)
print(df)

    Payment ID  total_bill   tip  gender smoker   day    time  size  \
0      Sun2959       16.99  1.01  Female     No   Sun  Dinner     2
1      Sun4608       10.34  1.66    Male     No   Sun  Dinner     3
2      Sun4458       21.01  3.50    Male     No   Sun  Dinner     3
3      Sun5260       23.68  3.31    Male     No   Sun  Dinner     2
4      Sun2251       24.59  3.61  Female     No   Sun  Dinner     4
..         ...         ...   ...     ...    ...   ...     ...   ...
239    Sat2657       29.03  5.92    Male     No   Sat  Dinner     3
240    Sat1766       27.18  2.00  Female    Yes   Sat  Dinner     2
241    Sat3880       22.67  2.00    Male    Yes   Sat  Dinner     2
242      Sat17       17.82  1.75    Male     No   Sat  Dinner     2
243    Thur672       18.78  3.00  Female     No  Thur  Dinner     2

     price_per_person          Payer Name     CC Number
0                8.49  Christy Cunningham  3.560330e+15
1                3.45      Douglas Tucker  4.478070e+15
2                7.00      Travis Walters  6.011810e+15
3               11.84    Nathaniel Harris  4.676140e+15
4                6.15        Tonya Carter  4.832730e+15
..                ...                 ...           ...
239              9.68       Michael Avila  5.296070e+15
240             13.59      Monica Sanders  3.506810e+15
241             11.34          Keith Wong  6.011890e+15
242              8.91        Dennis Dixon  4.375220e+12
243              9.39     Michelle Hardin  3.511450e+15

[244 rows x 11 columns]

In [278]:
# Conditions
print(df['total_bill'] < 30)
bool_series = df['total_bill'] > 30
print(df[bool_series])

print(df[df['total_bill'] > 30])

0      True
1      True
2      True
3      True
4      True
       ...
239    True
240    True
241    True
242    True
243    True
Name: total_bill, Length: 244, dtype: bool
    Payment ID  total_bill    tip  gender smoker   day    time  size  \
11     Sun6686       35.26   5.00  Female     No   Sun  Dinner     4
23      Sat239       39.42   7.58    Male     No   Sat  Dinner     4
39     Sat6373       31.27   5.00    Male     No   Sat  Dinner     3
44     Sun2274       30.40   5.60    Male     No   Sun  Dinner     4
47     Sun9677       32.40   6.00    Male     No   Sun  Dinner     4
52     Sun6165       34.81   5.20  Female     No   Sun  Dinner     4
56     Sat8903       38.01   3.00    Male    Yes   Sat  Dinner     4
59     Sat8139       48.27   6.73    Male     No   Sat  Dinner     4
83    Thur8801       32.68   5.00    Male    Yes  Thur   Lunch     2
85    Thur7972       34.83   5.17  Female     No  Thur   Lunch     4
95     Fri9628       40.17   4.73    Male    Yes   Fri  Dinner     4
102    Sat6240       44.30   2.50  Female    Yes   Sat  Dinner     3
112     Sun591       38.07   4.00    Male     No   Sun  Dinner     3
141   Thur1025       34.30   6.70    Male     No  Thur   Lunch     6
142   Thur3621       41.19   5.00    Male     No  Thur   Lunch     5
156    Sun7518       48.17   5.00    Male     No   Sun  Dinner     6
167    Sun3719       31.71   4.50    Male     No   Sun  Dinner     4
170    Sat1954       50.81  10.00    Male    Yes   Sat  Dinner     3
173    Sun9335       31.85   3.18    Male    Yes   Sun  Dinner     2
175    Sun5109       32.90   3.11    Male    Yes   Sun  Dinner     2
179    Sun9851       34.63   3.55    Male    Yes   Sun  Dinner     2
180    Sun7544       34.65   3.68    Male    Yes   Sun  Dinner     4
182    Sun2337       45.35   3.50    Male    Yes   Sun  Dinner     3
184    Sun5140       40.55   3.00    Male    Yes   Sun  Dinner     2
187    Sun9987       30.46   2.00    Male    Yes   Sun  Dinner     5
197   Thur9313       43.11   5.00  Female    Yes  Thur   Lunch     4
207    Sat4505       38.73   3.00    Male    Yes   Sat  Dinner     4
210    Sat8361       30.06   2.00    Male    Yes   Sat  Dinner     3
212    Sat4590       48.33   9.00    Male     No   Sat  Dinner     4
219    Sat8863       30.14   3.09  Female    Yes   Sat  Dinner     4
237    Sat2929       32.83   1.17    Male    Yes   Sat  Dinner     2
238    Sat9777       35.83   4.67  Female     No   Sat  Dinner     3

     price_per_person             Payer Name     CC Number
11               8.82           Diane Macias  4.577820e+15
23               9.86         Lance Peterson  3.542580e+15
39              10.42      Mr. Brandon Berry  6.011530e+15
44               7.60            Todd Cooper  5.038470e+11
47               8.10           James Barnes  3.552000e+15
52               8.70           Emily Daniel  4.291280e+15
56               9.50  James Christensen DDS  3.497940e+14
59              12.07            Brian Ortiz  6.596450e+15
83              16.34          Daniel Murphy  5.356180e+15
85               8.71            Shawna Cook  6.011790e+15
95              10.04          Aaron Bentley  1.800270e+14
102             14.77          Heather Cohen  3.797710e+14
112             12.69             Jeff Lopez  3.572870e+15
141              5.72         Steven Carlson  3.526520e+15
142              8.24           Eric Andrews  4.356530e+15
156              8.03          Ryan Gonzales  3.523150e+15
167              7.93         Michael Lawson  3.566290e+15
170             16.94          Gregory Clark  5.473850e+15
173             15.92            Scott Perez  3.577120e+15
175             16.45        Nathan Reynolds  3.703070e+14
179             17.32           Brian Bailey  3.466560e+14
180              8.66       James Hebert DDS  6.761690e+11
182             15.12           Jose Parsons  4.112210e+15
184             20.27            Stephen Cox  3.547800e+15
187              6.09          David Barrett  4.792880e+15
197             10.78            Brooke Soto  5.544900e+15
207              9.68          Ricky Ramirez  3.478180e+14
210             10.02          Shawn Mendoza  3.018400e+13
212             12.08        Alex Williamson  6.762190e+11
219              7.54           Shelby House  5.020970e+11
237             16.42           Thomas Brown  4.284720e+15
238             11.94         Kimberly Crane  6.761840e+11
    Payment ID  total_bill    tip  gender smoker   day    time  size  \
11     Sun6686       35.26   5.00  Female     No   Sun  Dinner     4
23      Sat239       39.42   7.58    Male     No   Sat  Dinner     4
39     Sat6373       31.27   5.00    Male     No   Sat  Dinner     3
44     Sun2274       30.40   5.60    Male     No   Sun  Dinner     4
47     Sun9677       32.40   6.00    Male     No   Sun  Dinner     4
52     Sun6165       34.81   5.20  Female     No   Sun  Dinner     4
56     Sat8903       38.01   3.00    Male    Yes   Sat  Dinner     4
59     Sat8139       48.27   6.73    Male     No   Sat  Dinner     4
83    Thur8801       32.68   5.00    Male    Yes  Thur   Lunch     2
85    Thur7972       34.83   5.17  Female     No  Thur   Lunch     4
95     Fri9628       40.17   4.73    Male    Yes   Fri  Dinner     4
102    Sat6240       44.30   2.50  Female    Yes   Sat  Dinner     3
112     Sun591       38.07   4.00    Male     No   Sun  Dinner     3
141   Thur1025       34.30   6.70    Male     No  Thur   Lunch     6
142   Thur3621       41.19   5.00    Male     No  Thur   Lunch     5
156    Sun7518       48.17   5.00    Male     No   Sun  Dinner     6
167    Sun3719       31.71   4.50    Male     No   Sun  Dinner     4
170    Sat1954       50.81  10.00    Male    Yes   Sat  Dinner     3
173    Sun9335       31.85   3.18    Male    Yes   Sun  Dinner     2
175    Sun5109       32.90   3.11    Male    Yes   Sun  Dinner     2
179    Sun9851       34.63   3.55    Male    Yes   Sun  Dinner     2
180    Sun7544       34.65   3.68    Male    Yes   Sun  Dinner     4
182    Sun2337       45.35   3.50    Male    Yes   Sun  Dinner     3
184    Sun5140       40.55   3.00    Male    Yes   Sun  Dinner     2
187    Sun9987       30.46   2.00    Male    Yes   Sun  Dinner     5
197   Thur9313       43.11   5.00  Female    Yes  Thur   Lunch     4
207    Sat4505       38.73   3.00    Male    Yes   Sat  Dinner     4
210    Sat8361       30.06   2.00    Male    Yes   Sat  Dinner     3
212    Sat4590       48.33   9.00    Male     No   Sat  Dinner     4
219    Sat8863       30.14   3.09  Female    Yes   Sat  Dinner     4
237    Sat2929       32.83   1.17    Male    Yes   Sat  Dinner     2
238    Sat9777       35.83   4.67  Female     No   Sat  Dinner     3

     price_per_person             Payer Name     CC Number
11               8.82           Diane Macias  4.577820e+15
23               9.86         Lance Peterson  3.542580e+15
39              10.42      Mr. Brandon Berry  6.011530e+15
44               7.60            Todd Cooper  5.038470e+11
47               8.10           James Barnes  3.552000e+15
52               8.70           Emily Daniel  4.291280e+15
56               9.50  James Christensen DDS  3.497940e+14
59              12.07            Brian Ortiz  6.596450e+15
83              16.34          Daniel Murphy  5.356180e+15
85               8.71            Shawna Cook  6.011790e+15
95              10.04          Aaron Bentley  1.800270e+14
102             14.77          Heather Cohen  3.797710e+14
112             12.69             Jeff Lopez  3.572870e+15
141              5.72         Steven Carlson  3.526520e+15
142              8.24           Eric Andrews  4.356530e+15
156              8.03          Ryan Gonzales  3.523150e+15
167              7.93         Michael Lawson  3.566290e+15
170             16.94          Gregory Clark  5.473850e+15
173             15.92            Scott Perez  3.577120e+15
175             16.45        Nathan Reynolds  3.703070e+14
179             17.32           Brian Bailey  3.466560e+14
180              8.66       James Hebert DDS  6.761690e+11
182             15.12           Jose Parsons  4.112210e+15
184             20.27            Stephen Cox  3.547800e+15
187              6.09          David Barrett  4.792880e+15
197             10.78            Brooke Soto  5.544900e+15
207              9.68          Ricky Ramirez  3.478180e+14
210             10.02          Shawn Mendoza  3.018400e+13
212             12.08        Alex Williamson  6.762190e+11
219              7.54           Shelby House  5.020970e+11
237             16.42           Thomas Brown  4.284720e+15
238             11.94         Kimberly Crane  6.761840e+11

In [279]:
# Another syntax
print(df['total_bill'] > 30)
print(df[df['total_bill'] > 30])
print(df[df['gender'] == 'Male'])

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Name: total_bill, Length: 244, dtype: bool
    Payment ID  total_bill    tip  gender smoker   day    time  size  \
11     Sun6686       35.26   5.00  Female     No   Sun  Dinner     4
23      Sat239       39.42   7.58    Male     No   Sat  Dinner     4
39     Sat6373       31.27   5.00    Male     No   Sat  Dinner     3
44     Sun2274       30.40   5.60    Male     No   Sun  Dinner     4
47     Sun9677       32.40   6.00    Male     No   Sun  Dinner     4
52     Sun6165       34.81   5.20  Female     No   Sun  Dinner     4
56     Sat8903       38.01   3.00    Male    Yes   Sat  Dinner     4
59     Sat8139       48.27   6.73    Male     No   Sat  Dinner     4
83    Thur8801       32.68   5.00    Male    Yes  Thur   Lunch     2
85    Thur7972       34.83   5.17  Female     No  Thur   Lunch     4
95     Fri9628       40.17   4.73    Male    Yes   Fri  Dinner     4
102    Sat6240       44.30   2.50  Female    Yes   Sat  Dinner     3
112     Sun591       38.07   4.00    Male     No   Sun  Dinner     3
141   Thur1025       34.30   6.70    Male     No  Thur   Lunch     6
142   Thur3621       41.19   5.00    Male     No  Thur   Lunch     5
156    Sun7518       48.17   5.00    Male     No   Sun  Dinner     6
167    Sun3719       31.71   4.50    Male     No   Sun  Dinner     4
170    Sat1954       50.81  10.00    Male    Yes   Sat  Dinner     3
173    Sun9335       31.85   3.18    Male    Yes   Sun  Dinner     2
175    Sun5109       32.90   3.11    Male    Yes   Sun  Dinner     2
179    Sun9851       34.63   3.55    Male    Yes   Sun  Dinner     2
180    Sun7544       34.65   3.68    Male    Yes   Sun  Dinner     4
182    Sun2337       45.35   3.50    Male    Yes   Sun  Dinner     3
184    Sun5140       40.55   3.00    Male    Yes   Sun  Dinner     2
187    Sun9987       30.46   2.00    Male    Yes   Sun  Dinner     5
197   Thur9313       43.11   5.00  Female    Yes  Thur   Lunch     4
207    Sat4505       38.73   3.00    Male    Yes   Sat  Dinner     4
210    Sat8361       30.06   2.00    Male    Yes   Sat  Dinner     3
212    Sat4590       48.33   9.00    Male     No   Sat  Dinner     4
219    Sat8863       30.14   3.09  Female    Yes   Sat  Dinner     4
237    Sat2929       32.83   1.17    Male    Yes   Sat  Dinner     2
238    Sat9777       35.83   4.67  Female     No   Sat  Dinner     3

     price_per_person             Payer Name     CC Number
11               8.82           Diane Macias  4.577820e+15
23               9.86         Lance Peterson  3.542580e+15
39              10.42      Mr. Brandon Berry  6.011530e+15
44               7.60            Todd Cooper  5.038470e+11
47               8.10           James Barnes  3.552000e+15
52               8.70           Emily Daniel  4.291280e+15
56               9.50  James Christensen DDS  3.497940e+14
59              12.07            Brian Ortiz  6.596450e+15
83              16.34          Daniel Murphy  5.356180e+15
85               8.71            Shawna Cook  6.011790e+15
95              10.04          Aaron Bentley  1.800270e+14
102             14.77          Heather Cohen  3.797710e+14
112             12.69             Jeff Lopez  3.572870e+15
141              5.72         Steven Carlson  3.526520e+15
142              8.24           Eric Andrews  4.356530e+15
156              8.03          Ryan Gonzales  3.523150e+15
167              7.93         Michael Lawson  3.566290e+15
170             16.94          Gregory Clark  5.473850e+15
173             15.92            Scott Perez  3.577120e+15
175             16.45        Nathan Reynolds  3.703070e+14
179             17.32           Brian Bailey  3.466560e+14
180              8.66       James Hebert DDS  6.761690e+11
182             15.12           Jose Parsons  4.112210e+15
184             20.27            Stephen Cox  3.547800e+15
187              6.09          David Barrett  4.792880e+15
197             10.78            Brooke Soto  5.544900e+15
207              9.68          Ricky Ramirez  3.478180e+14
210             10.02          Shawn Mendoza  3.018400e+13
212             12.08        Alex Williamson  6.762190e+11
219              7.54           Shelby House  5.020970e+11
237             16.42           Thomas Brown  4.284720e+15
238             11.94         Kimberly Crane  6.761840e+11
    Payment ID  total_bill   tip gender smoker  day    time  size  \
1      Sun4608       10.34  1.66   Male     No  Sun  Dinner     3
2      Sun4458       21.01  3.50   Male     No  Sun  Dinner     3
3      Sun5260       23.68  3.31   Male     No  Sun  Dinner     2
5      Sun9679       25.29  4.71   Male     No  Sun  Dinner     4
6      Sun5985        8.77  2.00   Male     No  Sun  Dinner     2
..         ...         ...   ...    ...    ...  ...     ...   ...
236    Sat5032       12.60  1.00   Male    Yes  Sat  Dinner     2
237    Sat2929       32.83  1.17   Male    Yes  Sat  Dinner     2
239    Sat2657       29.03  5.92   Male     No  Sat  Dinner     3
241    Sat3880       22.67  2.00   Male    Yes  Sat  Dinner     2
242      Sat17       17.82  1.75   Male     No  Sat  Dinner     2

     price_per_person          Payer Name     CC Number
1                3.45      Douglas Tucker  4.478070e+15
2                7.00      Travis Walters  6.011810e+15
3               11.84    Nathaniel Harris  4.676140e+15
5                6.32          Erik Smith  2.131400e+14
6                4.38  Kristopher Johnson  2.223730e+15
..                ...                 ...           ...
236              6.30       Matthew Myers  3.543680e+15
237             16.42        Thomas Brown  4.284720e+15
239              9.68       Michael Avila  5.296070e+15
241             11.34          Keith Wong  6.011890e+15
242              8.91        Dennis Dixon  4.375220e+12

[157 rows x 11 columns]

In [280]:
# Multiple conditions
df_new = df[(df['total_bill'] > 30) & (df['gender'] == 'Male')]
print(len(df_new))
print(df_new)

25
    Payment ID  total_bill    tip gender smoker   day    time  size  \
23      Sat239       39.42   7.58   Male     No   Sat  Dinner     4
39     Sat6373       31.27   5.00   Male     No   Sat  Dinner     3
44     Sun2274       30.40   5.60   Male     No   Sun  Dinner     4
47     Sun9677       32.40   6.00   Male     No   Sun  Dinner     4
56     Sat8903       38.01   3.00   Male    Yes   Sat  Dinner     4
59     Sat8139       48.27   6.73   Male     No   Sat  Dinner     4
83    Thur8801       32.68   5.00   Male    Yes  Thur   Lunch     2
95     Fri9628       40.17   4.73   Male    Yes   Fri  Dinner     4
112     Sun591       38.07   4.00   Male     No   Sun  Dinner     3
141   Thur1025       34.30   6.70   Male     No  Thur   Lunch     6
142   Thur3621       41.19   5.00   Male     No  Thur   Lunch     5
156    Sun7518       48.17   5.00   Male     No   Sun  Dinner     6
167    Sun3719       31.71   4.50   Male     No   Sun  Dinner     4
170    Sat1954       50.81  10.00   Male    Yes   Sat  Dinner     3
173    Sun9335       31.85   3.18   Male    Yes   Sun  Dinner     2
175    Sun5109       32.90   3.11   Male    Yes   Sun  Dinner     2
179    Sun9851       34.63   3.55   Male    Yes   Sun  Dinner     2
180    Sun7544       34.65   3.68   Male    Yes   Sun  Dinner     4
182    Sun2337       45.35   3.50   Male    Yes   Sun  Dinner     3
184    Sun5140       40.55   3.00   Male    Yes   Sun  Dinner     2
187    Sun9987       30.46   2.00   Male    Yes   Sun  Dinner     5
207    Sat4505       38.73   3.00   Male    Yes   Sat  Dinner     4
210    Sat8361       30.06   2.00   Male    Yes   Sat  Dinner     3
212    Sat4590       48.33   9.00   Male     No   Sat  Dinner     4
237    Sat2929       32.83   1.17   Male    Yes   Sat  Dinner     2

     price_per_person             Payer Name     CC Number
23               9.86         Lance Peterson  3.542580e+15
39              10.42      Mr. Brandon Berry  6.011530e+15
44               7.60            Todd Cooper  5.038470e+11
47               8.10           James Barnes  3.552000e+15
56               9.50  James Christensen DDS  3.497940e+14
59              12.07            Brian Ortiz  6.596450e+15
83              16.34          Daniel Murphy  5.356180e+15
95              10.04          Aaron Bentley  1.800270e+14
112             12.69             Jeff Lopez  3.572870e+15
141              5.72         Steven Carlson  3.526520e+15
142              8.24           Eric Andrews  4.356530e+15
156              8.03          Ryan Gonzales  3.523150e+15
167              7.93         Michael Lawson  3.566290e+15
170             16.94          Gregory Clark  5.473850e+15
173             15.92            Scott Perez  3.577120e+15
175             16.45        Nathan Reynolds  3.703070e+14
179             17.32           Brian Bailey  3.466560e+14
180              8.66       James Hebert DDS  6.761690e+11
182             15.12           Jose Parsons  4.112210e+15
184             20.27            Stephen Cox  3.547800e+15
187              6.09          David Barrett  4.792880e+15
207              9.68          Ricky Ramirez  3.478180e+14
210             10.02          Shawn Mendoza  3.018400e+13
212             12.08        Alex Williamson  6.762190e+11
237             16.42           Thomas Brown  4.284720e+15

In [281]:
# Multiple conditions
df_new = df[(df['total_bill'] > 30) & ~(df['gender'] == 'Male')]
print(len(df_new))
print(df.head(3))

7
  Payment ID  total_bill   tip  gender smoker  day    time  size  \
0    Sun2959       16.99  1.01  Female     No  Sun  Dinner     2
1    Sun4608       10.34  1.66    Male     No  Sun  Dinner     3
2    Sun4458       21.01  3.50    Male     No  Sun  Dinner     3

   price_per_person          Payer Name     CC Number
0              8.49  Christy Cunningham  3.560330e+15
1              3.45      Douglas Tucker  4.478070e+15
2              7.00      Travis Walters  6.011810e+15

In [282]:
# Multiple conditions
df_new = df[(df['total_bill'] > 30) & (df['gender'] != 'Male')]
print(len(df_new))
print(df.head(3))

7
  Payment ID  total_bill   tip  gender smoker  day    time  size  \
0    Sun2959       16.99  1.01  Female     No  Sun  Dinner     2
1    Sun4608       10.34  1.66    Male     No  Sun  Dinner     3
2    Sun4458       21.01  3.50    Male     No  Sun  Dinner     3

   price_per_person          Payer Name     CC Number
0              8.49  Christy Cunningham  3.560330e+15
1              3.45      Douglas Tucker  4.478070e+15
2              7.00      Travis Walters  6.011810e+15

In [283]:
#Multiple conditions

df_new = df[(df['total_bill'] > 30) & (df['gender']=='Male')]
print(df_new)

    Payment ID  total_bill    tip gender smoker   day    time  size  \
23      Sat239       39.42   7.58   Male     No   Sat  Dinner     4
39     Sat6373       31.27   5.00   Male     No   Sat  Dinner     3
44     Sun2274       30.40   5.60   Male     No   Sun  Dinner     4
47     Sun9677       32.40   6.00   Male     No   Sun  Dinner     4
56     Sat8903       38.01   3.00   Male    Yes   Sat  Dinner     4
59     Sat8139       48.27   6.73   Male     No   Sat  Dinner     4
83    Thur8801       32.68   5.00   Male    Yes  Thur   Lunch     2
95     Fri9628       40.17   4.73   Male    Yes   Fri  Dinner     4
112     Sun591       38.07   4.00   Male     No   Sun  Dinner     3
141   Thur1025       34.30   6.70   Male     No  Thur   Lunch     6
142   Thur3621       41.19   5.00   Male     No  Thur   Lunch     5
156    Sun7518       48.17   5.00   Male     No   Sun  Dinner     6
167    Sun3719       31.71   4.50   Male     No   Sun  Dinner     4
170    Sat1954       50.81  10.00   Male    Yes   Sat  Dinner     3
173    Sun9335       31.85   3.18   Male    Yes   Sun  Dinner     2
175    Sun5109       32.90   3.11   Male    Yes   Sun  Dinner     2
179    Sun9851       34.63   3.55   Male    Yes   Sun  Dinner     2
180    Sun7544       34.65   3.68   Male    Yes   Sun  Dinner     4
182    Sun2337       45.35   3.50   Male    Yes   Sun  Dinner     3
184    Sun5140       40.55   3.00   Male    Yes   Sun  Dinner     2
187    Sun9987       30.46   2.00   Male    Yes   Sun  Dinner     5
207    Sat4505       38.73   3.00   Male    Yes   Sat  Dinner     4
210    Sat8361       30.06   2.00   Male    Yes   Sat  Dinner     3
212    Sat4590       48.33   9.00   Male     No   Sat  Dinner     4
237    Sat2929       32.83   1.17   Male    Yes   Sat  Dinner     2

     price_per_person             Payer Name     CC Number
23               9.86         Lance Peterson  3.542580e+15
39              10.42      Mr. Brandon Berry  6.011530e+15
44               7.60            Todd Cooper  5.038470e+11
47               8.10           James Barnes  3.552000e+15
56               9.50  James Christensen DDS  3.497940e+14
59              12.07            Brian Ortiz  6.596450e+15
83              16.34          Daniel Murphy  5.356180e+15
95              10.04          Aaron Bentley  1.800270e+14
112             12.69             Jeff Lopez  3.572870e+15
141              5.72         Steven Carlson  3.526520e+15
142              8.24           Eric Andrews  4.356530e+15
156              8.03          Ryan Gonzales  3.523150e+15
167              7.93         Michael Lawson  3.566290e+15
170             16.94          Gregory Clark  5.473850e+15
173             15.92            Scott Perez  3.577120e+15
175             16.45        Nathan Reynolds  3.703070e+14
179             17.32           Brian Bailey  3.466560e+14
180              8.66       James Hebert DDS  6.761690e+11
182             15.12           Jose Parsons  4.112210e+15
184             20.27            Stephen Cox  3.547800e+15
187              6.09          David Barrett  4.792880e+15
207              9.68          Ricky Ramirez  3.478180e+14
210             10.02          Shawn Mendoza  3.018400e+13
212             12.08        Alex Williamson  6.762190e+11
237             16.42           Thomas Brown  4.284720e+15

In [284]:
df_new = df[(df['total_bill'] > 30) & ~(df['gender']=='Male')]
print(df_new)

    Payment ID  total_bill   tip  gender smoker   day    time  size  \
11     Sun6686       35.26  5.00  Female     No   Sun  Dinner     4
52     Sun6165       34.81  5.20  Female     No   Sun  Dinner     4
85    Thur7972       34.83  5.17  Female     No  Thur   Lunch     4
102    Sat6240       44.30  2.50  Female    Yes   Sat  Dinner     3
197   Thur9313       43.11  5.00  Female    Yes  Thur   Lunch     4
219    Sat8863       30.14  3.09  Female    Yes   Sat  Dinner     4
238    Sat9777       35.83  4.67  Female     No   Sat  Dinner     3

     price_per_person      Payer Name     CC Number
11               8.82    Diane Macias  4.577820e+15
52               8.70    Emily Daniel  4.291280e+15
85               8.71     Shawna Cook  6.011790e+15
102             14.77   Heather Cohen  3.797710e+14
197             10.78     Brooke Soto  5.544900e+15
219              7.54    Shelby House  5.020970e+11
238             11.94  Kimberly Crane  6.761840e+11

In [285]:
df_new = df[(df['total_bill'] > 30) & (df['gender']!='Male')]
print(df_new)

    Payment ID  total_bill   tip  gender smoker   day    time  size  \
11     Sun6686       35.26  5.00  Female     No   Sun  Dinner     4
52     Sun6165       34.81  5.20  Female     No   Sun  Dinner     4
85    Thur7972       34.83  5.17  Female     No  Thur   Lunch     4
102    Sat6240       44.30  2.50  Female    Yes   Sat  Dinner     3
197   Thur9313       43.11  5.00  Female    Yes  Thur   Lunch     4
219    Sat8863       30.14  3.09  Female    Yes   Sat  Dinner     4
238    Sat9777       35.83  4.67  Female     No   Sat  Dinner     3

     price_per_person      Payer Name     CC Number
11               8.82    Diane Macias  4.577820e+15
52               8.70    Emily Daniel  4.291280e+15
85               8.71     Shawna Cook  6.011790e+15
102             14.77   Heather Cohen  3.797710e+14
197             10.78     Brooke Soto  5.544900e+15
219              7.54    Shelby House  5.020970e+11
238             11.94  Kimberly Crane  6.761840e+11

In [286]:
df_new = df[(df['total_bill'] > 30) | (df['tip'] > 5)]
print(df_new)

    Payment ID  total_bill    tip  gender smoker   day    time  size  \
11     Sun6686       35.26   5.00  Female     No   Sun  Dinner     4
23      Sat239       39.42   7.58    Male     No   Sat  Dinner     4
39     Sat6373       31.27   5.00    Male     No   Sat  Dinner     3
44     Sun2274       30.40   5.60    Male     No   Sun  Dinner     4
47     Sun9677       32.40   6.00    Male     No   Sun  Dinner     4
52     Sun6165       34.81   5.20  Female     No   Sun  Dinner     4
56     Sat8903       38.01   3.00    Male    Yes   Sat  Dinner     4
59     Sat8139       48.27   6.73    Male     No   Sat  Dinner     4
83    Thur8801       32.68   5.00    Male    Yes  Thur   Lunch     2
85    Thur7972       34.83   5.17  Female     No  Thur   Lunch     4
88    Thur9003       24.71   5.85    Male     No  Thur   Lunch     2
95     Fri9628       40.17   4.73    Male    Yes   Fri  Dinner     4
102    Sat6240       44.30   2.50  Female    Yes   Sat  Dinner     3
112     Sun591       38.07   4.00    Male     No   Sun  Dinner     3
116      Sun22       29.93   5.07    Male     No   Sun  Dinner     4
141   Thur1025       34.30   6.70    Male     No  Thur   Lunch     6
142   Thur3621       41.19   5.00    Male     No  Thur   Lunch     5
155    Sun9176       29.85   5.14  Female     No   Sun  Dinner     5
156    Sun7518       48.17   5.00    Male     No   Sun  Dinner     6
167    Sun3719       31.71   4.50    Male     No   Sun  Dinner     4
170    Sat1954       50.81  10.00    Male    Yes   Sat  Dinner     3
172    Sun9209        7.25   5.15    Male    Yes   Sun  Dinner     2
173    Sun9335       31.85   3.18    Male    Yes   Sun  Dinner     2
175    Sun5109       32.90   3.11    Male    Yes   Sun  Dinner     2
179    Sun9851       34.63   3.55    Male    Yes   Sun  Dinner     2
180    Sun7544       34.65   3.68    Male    Yes   Sun  Dinner     4
181    Sun3402       23.33   5.65    Male    Yes   Sun  Dinner     2
182    Sun2337       45.35   3.50    Male    Yes   Sun  Dinner     3
183    Sun6059       23.17   6.50    Male    Yes   Sun  Dinner     4
184    Sun5140       40.55   3.00    Male    Yes   Sun  Dinner     2
187    Sun9987       30.46   2.00    Male    Yes   Sun  Dinner     5
197   Thur9313       43.11   5.00  Female    Yes  Thur   Lunch     4
207    Sat4505       38.73   3.00    Male    Yes   Sat  Dinner     4
210    Sat8361       30.06   2.00    Male    Yes   Sat  Dinner     3
211    Sat6735       25.89   5.16    Male    Yes   Sat  Dinner     4
212    Sat4590       48.33   9.00    Male     No   Sat  Dinner     4
214    Sat3374       28.17   6.50  Female    Yes   Sat  Dinner     3
219    Sat8863       30.14   3.09  Female    Yes   Sat  Dinner     4
237    Sat2929       32.83   1.17    Male    Yes   Sat  Dinner     2
238    Sat9777       35.83   4.67  Female     No   Sat  Dinner     3
239    Sat2657       29.03   5.92    Male     No   Sat  Dinner     3

     price_per_person             Payer Name     CC Number
11               8.82           Diane Macias  4.577820e+15
23               9.86         Lance Peterson  3.542580e+15
39              10.42      Mr. Brandon Berry  6.011530e+15
44               7.60            Todd Cooper  5.038470e+11
47               8.10           James Barnes  3.552000e+15
52               8.70           Emily Daniel  4.291280e+15
56               9.50  James Christensen DDS  3.497940e+14
59              12.07            Brian Ortiz  6.596450e+15
83              16.34          Daniel Murphy  5.356180e+15
85               8.71            Shawna Cook  6.011790e+15
88              12.36           Roger Taylor  4.410250e+12
95              10.04          Aaron Bentley  1.800270e+14
102             14.77          Heather Cohen  3.797710e+14
112             12.69             Jeff Lopez  3.572870e+15
116              7.48            Shawn Blake  4.689080e+15
141              5.72         Steven Carlson  3.526520e+15
142              8.24           Eric Andrews  4.356530e+15
155              5.97         Madison Wilson  4.210880e+15
156              8.03          Ryan Gonzales  3.523150e+15
167              7.93         Michael Lawson  3.566290e+15
170             16.94          Gregory Clark  5.473850e+15
172              3.62            Larry White  3.043260e+13
173             15.92            Scott Perez  3.577120e+15
175             16.45        Nathan Reynolds  3.703070e+14
179             17.32           Brian Bailey  3.466560e+14
180              8.66       James Hebert DDS  6.761690e+11
181             11.66              Jason Cox  6.556930e+15
182             15.12           Jose Parsons  4.112210e+15
183              5.79      Dr. Michael James  4.718500e+12
184             20.27            Stephen Cox  3.547800e+15
187              6.09          David Barrett  4.792880e+15
197             10.78            Brooke Soto  5.544900e+15
207              9.68          Ricky Ramirez  3.478180e+14
210             10.02          Shawn Mendoza  3.018400e+13
211              6.47         Christopher Li  6.011960e+15
212             12.08        Alex Williamson  6.762190e+11
214              9.39        Marissa Jackson  4.922300e+15
219              7.54           Shelby House  5.020970e+11
237             16.42           Thomas Brown  4.284720e+15
238             11.94         Kimberly Crane  6.761840e+11
239              9.68          Michael Avila  5.296070e+15

In [287]:
# Conditional is in operator

options = ['Sat', 'Sun']
print(df['day'].isin (options))
print(df[df['day'].isin (options)])

0       True
1       True
2       True
3       True
4       True
       ...
239     True
240     True
241     True
242     True
243    False
Name: day, Length: 244, dtype: bool
    Payment ID  total_bill   tip  gender smoker  day    time  size  \
0      Sun2959       16.99  1.01  Female     No  Sun  Dinner     2
1      Sun4608       10.34  1.66    Male     No  Sun  Dinner     3
2      Sun4458       21.01  3.50    Male     No  Sun  Dinner     3
3      Sun5260       23.68  3.31    Male     No  Sun  Dinner     2
4      Sun2251       24.59  3.61  Female     No  Sun  Dinner     4
..         ...         ...   ...     ...    ...  ...     ...   ...
238    Sat9777       35.83  4.67  Female     No  Sat  Dinner     3
239    Sat2657       29.03  5.92    Male     No  Sat  Dinner     3
240    Sat1766       27.18  2.00  Female    Yes  Sat  Dinner     2
241    Sat3880       22.67  2.00    Male    Yes  Sat  Dinner     2
242      Sat17       17.82  1.75    Male     No  Sat  Dinner     2

     price_per_person          Payer Name     CC Number
0                8.49  Christy Cunningham  3.560330e+15
1                3.45      Douglas Tucker  4.478070e+15
2                7.00      Travis Walters  6.011810e+15
3               11.84    Nathaniel Harris  4.676140e+15
4                6.15        Tonya Carter  4.832730e+15
..                ...                 ...           ...
238             11.94      Kimberly Crane  6.761840e+11
239              9.68       Michael Avila  5.296070e+15
240             13.59      Monica Sanders  3.506810e+15
241             11.34          Keith Wong  6.011890e+15
242              8.91        Dennis Dixon  4.375220e+12

[163 rows x 11 columns]

In [288]:
# sort_values
print(df.sort_values('tip'))

    Payment ID  total_bill    tip  gender smoker   day    time  size  \
67     Sat3455        3.07   1.00  Female    Yes   Sat  Dinner     1
236    Sat5032       12.60   1.00    Male    Yes   Sat  Dinner     2
92     Fri3780        5.75   1.00  Female    Yes   Fri  Dinner     2
111    Sat4801        7.25   1.00  Female     No   Sat  Dinner     1
0      Sun2959       16.99   1.01  Female     No   Sun  Dinner     2
..         ...         ...    ...     ...    ...   ...     ...   ...
141   Thur1025       34.30   6.70    Male     No  Thur   Lunch     6
59     Sat8139       48.27   6.73    Male     No   Sat  Dinner     4
23      Sat239       39.42   7.58    Male     No   Sat  Dinner     4
212    Sat4590       48.33   9.00    Male     No   Sat  Dinner     4
170    Sat1954       50.81  10.00    Male    Yes   Sat  Dinner     3

     price_per_person          Payer Name     CC Number
67               3.07       Tiffany Brock  4.359490e+15
236              6.30       Matthew Myers  3.543680e+15
92               2.88        Leah Ramirez  3.508910e+15
111              7.25         Terri Jones  3.559220e+15
0                8.49  Christy Cunningham  3.560330e+15
..                ...                 ...           ...
141              5.72      Steven Carlson  3.526520e+15
59              12.07         Brian Ortiz  6.596450e+15
23               9.86      Lance Peterson  3.542580e+15
212             12.08     Alex Williamson  6.762190e+11
170             16.94       Gregory Clark  5.473850e+15

[244 rows x 11 columns]

In [289]:
#correlation
print(df[['total_bill', 'tip']].corr())

            total_bill       tip
total_bill    1.000000  0.675734
tip           0.675734  1.000000

In [290]:
#idxmin and idxmax
print(df['total_bill'].max())
print(df['total_bill'].idxmax())
print(df['total_bill'].idxmin())
print(df.iloc[67])
print(df.iloc[170])

50.81
170
67
Payment ID                     Sat3455
total_bill                        3.07
tip                                1.0
gender                          Female
smoker                             Yes
day                                Sat
time                            Dinner
size                                 1
price_per_person                  3.07
Payer Name               Tiffany Brock
CC Number           4359490000000000.0
Name: 67, dtype: object
Payment ID                     Sat1954
total_bill                       50.81
tip                               10.0
gender                            Male
smoker                             Yes
day                                Sat
time                            Dinner
size                                 3
price_per_person                 16.94
Payer Name               Gregory Clark
CC Number           5473850000000000.0
Name: 170, dtype: object

In [291]:
#value_counts get count on categorical columns

print(df['smoker'].value_counts()) # Smokers and non-smokers
print(df['gender'].value_counts()) # Males and Females

smoker
No     151
Yes     93
Name: count, dtype: int64
gender
Male      157
Female     87
Name: count, dtype: int64

In [292]:
# unique
print(df['day'].unique())
print(df['day'].nunique())
print(df['time'].unique())
print(df['time'].nunique())

['Sun' 'Sat' 'Thur' 'Fri']
4
['Dinner' 'Lunch']
2

In [293]:
# Between options for inclusive are both, left, right, neither
print(df['total_bill'].between(10,20,inclusive='both'))
print(df[df['total_bill'].between(10,20,inclusive='both')])

0       True
1       True
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242     True
243     True
Name: total_bill, Length: 244, dtype: bool
    Payment ID  total_bill   tip  gender smoker   day    time  size  \
0      Sun2959       16.99  1.01  Female     No   Sun  Dinner     2
1      Sun4608       10.34  1.66    Male     No   Sun  Dinner     3
8      Sun6820       15.04  1.96    Male     No   Sun  Dinner     2
9      Sun3775       14.78  3.23    Male     No   Sun  Dinner     2
10     Sun2546       10.27  1.71    Male     No   Sun  Dinner     2
..         ...         ...   ...     ...    ...   ...     ...   ...
234    Sat7220       15.53  3.00    Male    Yes   Sat  Dinner     2
235    Sat4615       10.07  1.25    Male     No   Sat  Dinner     2
236    Sat5032       12.60  1.00    Male    Yes   Sat  Dinner     2
242      Sat17       17.82  1.75    Male     No   Sat  Dinner     2
243    Thur672       18.78  3.00  Female     No  Thur  Dinner     2

     price_per_person          Payer Name     CC Number
0                8.49  Christy Cunningham  3.560330e+15
1                3.45      Douglas Tucker  4.478070e+15
8                7.52     Joseph Mcdonald  3.522870e+15
9                7.39       Jerome Abbott  3.532120e+15
10               5.14       William Riley  5.662880e+11
..                ...                 ...           ...
234              7.76       Tracy Douglas  4.097940e+15
235              5.04       Sean Gonzalez  3.534020e+15
236              6.30       Matthew Myers  3.543680e+15
242              8.91        Dennis Dixon  4.375220e+12
243              9.39     Michelle Hardin  3.511450e+15

[130 rows x 11 columns]

In [294]:
# Sample data randomly
print(df.sample(5))         # 5 rows
print(df.sample(frac=0.1))  # 10% of rows

    Payment ID  total_bill   tip  gender smoker   day    time  size  \
210    Sat8361       30.06  2.00    Male    Yes   Sat  Dinner     3
66     Sat4750       16.45  2.47  Female     No   Sat  Dinner     2
16     Sun9715       10.33  1.67  Female     No   Sun  Dinner     3
109    Sat2614       14.31  4.00  Female    Yes   Sat  Dinner     2
118   Thur8084       12.43  1.80  Female     No  Thur   Lunch     2

     price_per_person           Payer Name     CC Number
210             10.02        Shawn Mendoza  3.018400e+13
66               8.22        Rachel Vaughn  3.569260e+15
16               3.44     Elizabeth Foster  4.240030e+15
109              7.16      Amanda Anderson  3.756390e+14
118              6.22  Dr. Caroline Tucker  5.020470e+11
    Payment ID  total_bill   tip  gender smoker   day    time  size  \
106    Sat7865       20.49  4.06    Male    Yes   Sat  Dinner     2
60     Sat2353       20.29  3.21    Male    Yes   Sat  Dinner     2
212    Sat4590       48.33  9.00    Male     No   Sat  Dinner     4
31     Sat4947       18.35  2.50    Male     No   Sat  Dinner     4
152    Sun5205       17.26  2.74    Male     No   Sun  Dinner     3
112     Sun591       38.07  4.00    Male     No   Sun  Dinner     3
80    Thur6453       19.44  3.00    Male    Yes  Thur   Lunch     2
41     Sun9460       17.46  2.54    Male     No   Sun  Dinner     2
155    Sun9176       29.85  5.14  Female     No   Sun  Dinner     5
232    Sat2124       11.61  3.39    Male     No   Sat  Dinner     2
127   Thur1512       14.52  2.00  Female     No  Thur   Lunch     2
158     Sun982       13.39  2.61  Female     No   Sun  Dinner     2
240    Sat1766       27.18  2.00  Female    Yes   Sat  Dinner     2
34     Sat8124       17.78  3.27    Male     No   Sat  Dinner     2
159    Sun1781       16.49  2.00    Male     No   Sun  Dinner     4
204   Thur2160       20.53  4.00    Male    Yes  Thur   Lunch     4
116      Sun22       29.93  5.07    Male     No   Sun  Dinner     4
55     Sun1118       19.49  3.51    Male     No   Sun  Dinner     2
70     Sat2100       12.02  1.97    Male     No   Sat  Dinner     2
40     Sat8549       16.04  2.24    Male     No   Sat  Dinner     3
229    Sat3943       22.12  2.88  Female    Yes   Sat  Dinner     2
176    Sun5961       17.89  2.00    Male    Yes   Sun  Dinner     2
86    Thur6793       13.03  2.00    Male     No  Thur   Lunch     2
168    Sat9795       10.59  1.61  Female    Yes   Sat  Dinner     2

     price_per_person        Payer Name     CC Number
106             10.24     Karl Mcdaniel  1.800240e+14
60              10.14    Anthony Mclean  3.476140e+14
212             12.08   Alex Williamson  6.762190e+11
31               4.59    Danny Santiago  6.304160e+11
152              5.75     Gregory Smith  4.292360e+12
112             12.69        Jeff Lopez  3.572870e+15
80               9.72      Louis Torres  3.884840e+13
41               8.73       David Boyer  3.536680e+15
155              5.97    Madison Wilson  4.210880e+15
232              5.80      James Taylor  6.011480e+15
127              7.26   Jessica Simmons  2.131020e+14
158              6.70       Ashley Boyd  3.571090e+15
240             13.59    Monica Sanders  3.506810e+15
34               8.89    Jacob Castillo  3.551490e+15
159              4.12  Christopher Soto  3.050180e+13
204              5.13         Scott Kim  3.570610e+15
116              7.48       Shawn Blake  4.689080e+15
55               9.74  Michael Hamilton  6.502230e+15
70               6.01         Max Brown  2.131400e+14
40               5.35      Adam Edwards  3.544450e+15
229             11.06  Jennifer Russell  4.793000e+12
176              8.94    Walter Simmons  6.011480e+15
86               6.52      Derek Thomas  2.131610e+14
168              5.30      Sara Jimenez  5.020530e+11

In [295]:
# nlargest and nsmallest
print(df.nlargest(10, 'tip'))
print(df.nsmallest(10, 'tip'))

    Payment ID  total_bill    tip  gender smoker   day    time  size  \
170    Sat1954       50.81  10.00    Male    Yes   Sat  Dinner     3
212    Sat4590       48.33   9.00    Male     No   Sat  Dinner     4
23      Sat239       39.42   7.58    Male     No   Sat  Dinner     4
59     Sat8139       48.27   6.73    Male     No   Sat  Dinner     4
141   Thur1025       34.30   6.70    Male     No  Thur   Lunch     6
183    Sun6059       23.17   6.50    Male    Yes   Sun  Dinner     4
214    Sat3374       28.17   6.50  Female    Yes   Sat  Dinner     3
47     Sun9677       32.40   6.00    Male     No   Sun  Dinner     4
239    Sat2657       29.03   5.92    Male     No   Sat  Dinner     3
88    Thur9003       24.71   5.85    Male     No  Thur   Lunch     2

     price_per_person         Payer Name     CC Number
170             16.94      Gregory Clark  5.473850e+15
212             12.08    Alex Williamson  6.762190e+11
23               9.86     Lance Peterson  3.542580e+15
59              12.07        Brian Ortiz  6.596450e+15
141              5.72     Steven Carlson  3.526520e+15
183              5.79  Dr. Michael James  4.718500e+12
214              9.39    Marissa Jackson  4.922300e+15
47               8.10       James Barnes  3.552000e+15
239              9.68      Michael Avila  5.296070e+15
88              12.36       Roger Taylor  4.410250e+12
    Payment ID  total_bill   tip  gender smoker   day    time  size  \
67     Sat3455        3.07  1.00  Female    Yes   Sat  Dinner     1
92     Fri3780        5.75  1.00  Female    Yes   Fri  Dinner     2
111    Sat4801        7.25  1.00  Female     No   Sat  Dinner     1
236    Sat5032       12.60  1.00    Male    Yes   Sat  Dinner     2
0      Sun2959       16.99  1.01  Female     No   Sun  Dinner     2
215    Sat6983       12.90  1.10  Female    Yes   Sat  Dinner     2
237    Sat2929       32.83  1.17    Male    Yes   Sat  Dinner     2
75     Sat5056       10.51  1.25    Male     No   Sat  Dinner     2
135   Thur6600        8.51  1.25  Female     No  Thur   Lunch     2
235    Sat4615       10.07  1.25    Male     No   Sat  Dinner     2

     price_per_person          Payer Name     CC Number
67               3.07       Tiffany Brock  4.359490e+15
92               2.88        Leah Ramirez  3.508910e+15
111              7.25         Terri Jones  3.559220e+15
236              6.30       Matthew Myers  3.543680e+15
0                8.49  Christy Cunningham  3.560330e+15
215              6.45        Jessica Owen  4.726900e+12
237             16.42        Thomas Brown  4.284720e+15
75               5.26       Kenneth Hayes  2.131420e+14
135              4.26      Rebecca Harris  4.320270e+15
235              5.04       Sean Gonzalez  3.534020e+15

In [296]:
# groupby functionality:
# 1. Splitting: The data is first split into groups based
# 2. Applying: A function (or multiple functions) is applic
# 3. Combining: The results of the function applications a into a new DataFram

In [297]:
# Splitting
df_grouped = df.groupby('gender')
print(df_grouped.head())  # Note that the output will not have any visible impact, a mention of grouping
# Changing the datatype of each column BEFORE grouping
df['Payment ID'] = df['Payment ID'].astype(str)
df['total_bill'] = df['total_bill'].astype(float)
df['tip'] = df['tip'].astype(float)
df['size'] = df['size'].astype(int)
df['price_per_person'] = df['price_per_person'].astype(float)

# Now group the DataFrame with the desired data types:
df_grouped = df.groupby('gender')

   Payment ID  total_bill   tip  gender smoker  day    time  size  \
0     Sun2959       16.99  1.01  Female     No  Sun  Dinner     2
1     Sun4608       10.34  1.66    Male     No  Sun  Dinner     3
2     Sun4458       21.01  3.50    Male     No  Sun  Dinner     3
3     Sun5260       23.68  3.31    Male     No  Sun  Dinner     2
4     Sun2251       24.59  3.61  Female     No  Sun  Dinner     4
5     Sun9679       25.29  4.71    Male     No  Sun  Dinner     4
6     Sun5985        8.77  2.00    Male     No  Sun  Dinner     2
11    Sun6686       35.26  5.00  Female     No  Sun  Dinner     4
14    Sun3848       14.83  3.02  Female     No  Sun  Dinner     2
16    Sun9715       10.33  1.67  Female     No  Sun  Dinner     3

    price_per_person          Payer Name     CC Number
0               8.49  Christy Cunningham  3.560330e+15
1               3.45      Douglas Tucker  4.478070e+15
2               7.00      Travis Walters  6.011810e+15
3              11.84    Nathaniel Harris  4.676140e+15
4               6.15        Tonya Carter  4.832730e+15
5               6.32          Erik Smith  2.131400e+14
6               4.38  Kristopher Johnson  2.223730e+15
11              8.82        Diane Macias  4.577820e+15
14              7.42       Vanessa Jones  3.001670e+13
16              3.44    Elizabeth Foster  4.240030e+15

In [303]:

# Applying
mean_tip_by_gender = df_grouped['tip'].mean() # Calculate the mean tip for each gender
print(mean_tip_by_gender)
print(df_grouped.count()) # Count works on all columns
print(df_grouped[['tip']].max()) # Only include numeric columns for max
print(df_grouped[['tip']].min()) # Only include numeric columns for min
print(df_grouped[['tip']].sum()) # Only include numeric columns for sum
print(df_grouped[['tip']].var()) # Only include numeric columns for variance
print(df_grouped[['tip']].std()) # Only include numeric columns for standard deviation
print(df_grouped.describe()) # describe works on all columns but might provide less meaningful results for non-numeric columns

mean     2.937915
sum     91.447500
dtype: float64
gender          8
day             8
tip     mean    8
        sum     8
dtype: int64
tip  mean      3.367222
     sum     186.780000
dtype: float64
tip  mean     2.575625
     sum     25.030000
dtype: float64
tip  mean     23.503321
     sum     731.580000
dtype: float64
tip  mean       0.074505
     sum     3865.473393
dtype: float64
tip  mean     0.272957
     sum     62.172931
dtype: float64
            tip
           mean         sum
count  8.000000    8.000000
mean   2.937915   91.447500
std    0.272957   62.172931
min    2.575625   25.030000
25%    2.759083   52.190000
50%    2.891060   80.435000
75%    3.118010  112.545000
max    3.367222  186.780000

In [306]:
#agg function
# Apply multiple aggregation functions to different columns when grouping data #Calculate both the mean and sum of the 'tip' column for each combination of # 'gender' and 'day'
# Group the DataFrame by both 'gender' and 'day' and calculate the mean and sum of 'tip' or each combination

df_grouped = df.groupby(['gender', 'day']).agg({'tip': ['mean', 'sum']}).reset_index()
print(df_grouped)

   gender   day       tip
                     mean     sum
0  Female   Fri  2.781111   25.03
1  Female   Sat  2.801786   78.45
2  Female   Sun  3.367222   60.61
3  Female  Thur  2.575625   82.42
4    Male   Fri  2.693000   26.93
5    Male   Sat  3.083898  181.95
6    Male   Sun  3.220345  186.78
7    Male  Thur  2.980333   89.41

In [309]:
#Rename the columns
df_grouped.columns = ['gender', 'day', 'mean tip', 'total tip']
print(df_grouped)

   gender   day  mean tip  total tip
0  Female   Fri  2.781111      25.03
1  Female   Sat  2.801786      78.45
2  Female   Sun  3.367222      60.61
3  Female  Thur  2.575625      82.42
4    Male   Fri  2.693000      26.93
5    Male   Sat  3.083898     181.95
6    Male   Sun  3.220345     186.78
7    Male  Thur  2.980333      89.41

------

In [ ]:
# Other index example
df_airbnb = pd.read_csv('AB_NYC_2019.csv')
print(len(df_airbnb))
print(df_airbnb.head())

In [ ]:
# Make ind as coliumn
df2 = df_airbnb.set_index('id')
print(df2.head(3))
print(df2['name'][3647])
print(df2.columns)
df2.reset_index(inplace=True)

In [ ]:
df2.set_index('host_name', inplace=True)
print(len(df2.loc['John']))
print(df2.loc['John'])
df2.reset_index(inplace=True)

In [ ]:
# Set pandas display options toshow all columns
numeric_column = df.select_dtypes(include=['float64', 'int64'])
print(numeric_column.head())

In [ ]:

# Include 'room_type' column in numeric_column DataFrame
numeric_column['room_type'] = df2['room_type']
print(numeric_column.head())

In [ ]:
# Print all the columns without break
pd.set_option('display.max_columns', None)

In [ ]:
df3 = numeric_column.groupby('room_type').mean()
print(df3)

In [ ]:
pd.reset_option('display.max_columns')

In [ ]:
print(df3.head())

In [ ]:
#Rows
print(df2.iloc[0])

In [ ]:
df2.set_index('host_id')
print(df2.loc[3831])